# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notes.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'notes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotes.proto\x12\x05notes\"1\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x03\"\x14\n\x06NoteId\x12\n\n\x02id\x18\x01 \x01(\x03\"\x18\n\x08NoteText\x12\x0c\n\x04text\x18\x01 \x01(\t\"@\n\nChangeNote\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x03 \x01(\x03\"2\n\nDeleteNote\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x18\n\x10\x65xpected_version\x18\x02 \x01(\x03\"\x07\n\x05\x45mpty\"&\n\x08NoteList\x12\x1a\n\x05notes\x18\x01 \x03(\x0b\x32\x0b.notes.Note2\xce\x01\n\x05Notes\x12&\n\x06\x43reate\x12\x0f.notes.NoteText\x1a\x0b.notes.Note\x12!\n\x03Get\x12\r.notes.NoteId\x1a\x0b.notes.Note\x12%\n\x04List\x12\x0c.notes.Empty\x1a\x0f.notes.NoteList\x12(\n\x06Update\x12\x11.notes.ChangeNote\x1a\x0b.notes.Note\x12)\n\x06\x44\x65lete\x12\x11.notes.DeleteNote\x1a\x0c.notes.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTE']._serialized_start=22
  _globals['_NOTE']._serialized_end=71
  _globals['_NOTEID']._serialized_start=73
  _globals['_NOTEID']._serialized_end=93
  _globals['_NOTETEXT']._serialized_start=95
  _globals['_NOTETEXT']._serialized_end=119
  _globals['_CHANGENOTE']._serialized_start=121
  _globals['_CHANGENOTE']._serialized_end=185
  _globals['_DELETENOTE']._serialized_start=187
  _globals['_DELETENOTE']._serialized_end=237
  _globals['_EMPTY']._serialized_start=239
  _globals['_EMPTY']._serialized_end=246
  _globals['_NOTELIST']._serialized_start=248
  _globals['_NOTELIST']._serialized_end=286
  _globals['_NOTES']._serialized_start=289
  _globals['_NOTES']._serialized_end=495
# @@protoc_insertion_point(module_scope)
